# secrets.nix builds alias as 
# env.key + env
# so the alias it builds from the toml are
# db1live db2live db1stg db2stg db1dev db2dev
# you get the point

[database.env.live]
db1 = { host="0.0.0.0", username="uname", password="pass" }
db2 = { host="0.0.0.0", username="uname", password="pass" }

[database.env.stg]
db1 = { host="0.0.0.0", username="uname", password="pass" }
db2 = { host="0.0.0.0", username="uname", password="pass" }

[database.env.dev]
db1 = { host="0.0.0.0", username="uname", password="pass" }
db2 = { host="0.0.0.0", username="uname", password="pass" }


# adds to networking hosts /etc/hosts
# for ssh username@<hostname>
[hostnames]
syslog = { ip="0.0.0.0", hostname="syslog" }
edge = { ip="0.0.0.0", hostname="edge" }




